# config/packages/security.yaml
security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    # users are stored in the database
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    mongodb_provider:
            id: App\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      lazy: true
      provider: mongodb_provider
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: bicycle
        always_use_default_target_path: true
      logout:
        path: app_logout
        target: app_login
  access_control:
    - { path: /login , role: PUBLIC_ACCESS}
    - { path: /register , role: PUBLIC_ACCESS}
    - { path: ^/.*, role: ROLE_USER}
    # - { path: ^/.*, role: PUBLIC_ACCESS}
